# Generated by Django 5.2.14 on 2026-06-03 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SND30Axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('completed', 'Complété')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('territory', models.CharField(blank=True, max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SDGTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
                ('sdg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='odd.sdg')),
            ],
        ),
        migrations.CreateModel(
            name='SDGIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('unit', models.CharField(default='Proportion/Count', max_length=100)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='odd.sdgtarget')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSDGAlignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdg_alignments', to='odd.project')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odd.sdgindicator')),
            ],
            options={
                'unique_together': {('project', 'indicator')},
            },
        ),
        migrations.CreateModel(
            name='ProjectSND30Alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snd30_alignments', to='odd.project')),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odd.snd30axis')),
            ],
            options={
                'unique_together': {('project', 'axis')},
            },
        ),
    ]
