# Generated by Django 5.2.14 on 2026-06-03 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='beneficiaries_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='localite',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='pcd_prd_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectsdgalignment',
            name='justification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'En préparation'), ('submitted', 'Soumis'), ('under_control', 'En contrôle'), ('validated', 'Validé'), ('rejected', 'Rejeté'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='snd30axis',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='KPIMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('proof_url', models.URLField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odd.sdgindicator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_measures', to='odd.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectWorkflowTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='odd.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odd.sector'),
        ),
    ]
