# Generated by Django 5.2.14 on 2026-06-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odd', '0002_sector_project_beneficiaries_count_project_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectworkflowtrace',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='projectworkflowtrace',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='project',
            name='beneficiaries_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='funding_source',
        ),
        migrations.RemoveField(
            model_name='project',
            name='localite',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pcd_prd_link',
        ),
        migrations.RemoveField(
            model_name='projectsdgalignment',
            name='justification',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('completed', 'Complété')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='snd30axis',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='KPIMeasure',
        ),
        migrations.DeleteModel(
            name='ProjectWorkflowTrace',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
