# Generated by Django 5.2.14 on 2026-06-06 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odd', '0005_add_sector_workflow_commune_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OddRoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('Responsable Projet', 'Responsable Projet'), ('Point Focal ODD', 'Point Focal ODD'), ('Validateur CTD', 'Validateur CTD'), ('Validateur ARRDEL', 'Validateur ARRDEL'), ('Admin CTD', 'Admin CTD'), ('Admin ARRDEL', 'Admin ARRDEL'), ('Responsable Sectoriel', 'Responsable Sectoriel'), ('Décideur', 'Décideur'), ('Partenaire', 'Partenaire'), ('Citoyen', 'Citoyen')], max_length=60)),
                ('motivation', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odd_role_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odd_role_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
