# Generated by Django 5.2.14 on 2026-06-06 13:05

import django.db.models.deletion
import odd.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odd', '0006_add_odd_role_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('type_document', models.CharField(choices=[('pdf', 'Document PDF'), ('image', 'Image / Photo / Scan'), ('excel', 'Tableur Excel / CSV'), ('word', 'Document Word'), ('autre', 'Autre')], default='pdf', max_length=10)),
                ('fichier', models.FileField(upload_to=odd.models.preuve_upload_path)),
                ('hash_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('taille', models.BigIntegerField(default=0)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preuves', to='odd.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preuves_deposees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_depot'],
            },
        ),
    ]
