# Generated by Django 5.2.14 on 2026-06-09 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odd', '0008_add_period_mesurekpi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('controlling_ctd', 'En contrôle CTD'), ('validated_ctd', 'Validé CTD'), ('controlling_arrdel', 'En contrôle ARRDEL'), ('validated', 'Validé'), ('rejected', 'Rejeté'), ('needs_completion', 'À compléter')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='CampagneReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField(blank=True, choices=[(1, 'T1'), (2, 'T2'), (3, 'T3'), (4, 'T4')], null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('open', 'Ouverte'), ('closed', 'Clôturée')], default='planned', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('trimestriel', 'Rapport trimestriel'), ('annuel', 'Rapport annuel'), ('portefeuille', 'Rapport portefeuille'), ('synthese', 'Note de synthèse décisionnelle')], max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('generated', 'Généré'), ('validated', 'Validé'), ('archived', 'Archivé')], default='generated', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='odd.campagnereporting')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='odd.period')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DonneeSectorielle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_type', models.CharField(choices=[('sante', 'Santé'), ('education', 'Éducation'), ('eau', 'Eau et assainissement'), ('infrastructure', 'Infrastructure'), ('energie', 'Énergie'), ('agriculture', 'Agriculture'), ('economie', 'Économie locale'), ('environnement', 'Environnement')], max_length=20)),
                ('taux_realisation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('population_beneficiaire', models.IntegerField(blank=True, null=True)),
                ('donnees_specifiques', models.JSONField(blank=True, default=dict)),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumise'), ('validated', 'Validée'), ('rejected', 'Rejetée')], default='draft', max_length=10)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees_sectorielles', to='odd.period')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees_sectorielles', to='odd.project')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donnees_sectorielles_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_saisie'],
                'constraints': [models.UniqueConstraint(fields=('project', 'sector_type', 'period'), name='unique_project_sector_period')],
            },
        ),
    ]
