# Generated by Django 5.2.14 on 2026-06-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odd', '0009_add_campagne_rapport_donneesectorielle_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='project',
            name='score_global',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='score_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='score_odd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='score_snd30',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
