# Generated by Django 5.2.14 on 2026-06-29 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('odd', '0010_project_grade_project_score_global_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCDObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune_nom', models.CharField(max_length=100)),
                ('secteur', models.CharField(blank=True, max_length=200)),
                ('programme', models.CharField(blank=True, max_length=300)),
                ('objectif_global', models.TextField()),
                ('code_objectif_global', models.CharField(blank=True, max_length=20)),
                ('objectif_specifique', models.TextField(blank=True)),
                ('resultats', models.TextField(blank=True)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcd_objectives', to='locations.commune')),
            ],
            options={
                'ordering': ['commune_nom', 'secteur', 'code_objectif_global'],
            },
        ),
    ]
