# Generated by Django 5.2.15 on 2026-07-14 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odd', '0011_pcd_objective'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GaddDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('sociale', 'Sociale'), ('ecologique', 'Écologique'), ('economique', 'Économique'), ('culturelle', 'Culturelle'), ('ethique', 'Éthique'), ('gouvernance', 'Gouvernance')], max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GaddEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gadd_evaluations', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gadd_evaluation', to='odd.project')),
            ],
        ),
        migrations.CreateModel(
            name='GaddTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('label', models.CharField(max_length=255)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='odd.gadddimension')),
            ],
            options={
                'ordering': ['dimension__order', 'number'],
                'unique_together': {('dimension', 'number')},
            },
        ),
        migrations.CreateModel(
            name='GaddObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('label', models.TextField()),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='odd.gaddtheme')),
            ],
            options={
                'ordering': ['theme__number', 'code'],
                'unique_together': {('theme', 'code')},
            },
        ),
        migrations.CreateModel(
            name='GaddObjectiveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(blank=True, choices=[(1, 'Souhaitable'), (2, 'Important'), (3, 'Indispensable')], null=True)),
                ('evaluation_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('justification', models.TextField(blank=True, default='')),
                ('actions', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='odd.gaddevaluation')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='odd.gaddobjective')),
            ],
            options={
                'unique_together': {('evaluation', 'objective')},
            },
        ),
    ]
