# Generated by Django 5.2.15 on 2026-07-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odd', '0012_gadddimension_gaddevaluation_gaddtheme_gaddobjective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaddevaluation',
            name='relevant_theme_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
