# Generated by Django 5.2.15 on 2026-07-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odd', '0013_gaddevaluation_relevant_theme_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdgindicator',
            name='frequency',
            field=models.CharField(choices=[('annuelle', 'Annuelle'), ('semestrielle', 'Semestrielle'), ('trimestrielle', 'Trimestrielle'), ('mensuelle', 'Mensuelle'), ('ponctuelle', 'Ponctuelle')], default='annuelle', max_length=15),
        ),
    ]
