# Generated by Django 5.2.15 on 2026-07-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odd', '0014_sdgindicator_frequency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonneeSectorielle',
        ),
    ]
