# Generated by Django 5.2.15 on 2026-07-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odd', '0015_delete_donneesectorielle'),
    ]

    operations = [
        migrations.AddField(
            model_name='snd30axis',
            name='pilier_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='snd30axis',
            name='pilier_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
